version: '3.8'

services:
  db:
    image: postgres:18-alpine
    container_name: flashpaper_db
    restart: always
    environment:
      POSTGRES_USER: flashuser
      POSTGRES_PASSWORD: flashpassword
      POSTGRES_DB: flashpaper_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: