version: '3.8'

services:
  api:
    build: .
    container_name: flashpaper_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_URL: ${DB_URL}
      JWT_SECRET: ${JWT_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      JANITOR_INTERVAL: ${JANITOR_INTERVAL}
      TOKEN_EXPIRATION: ${TOKEN_EXPIRATION}